// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://awsobkkubtognchzktsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3c29ia2t1YnRvZ25jaHprdHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MzQ5NzQsImV4cCI6MjA5MTQxMDk3NH0.Ss-JWCmTY4x84hEKGf5R5xRWv5RvNpTRxoqVbwOlsfg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);